In [1]:
import torch

# Test points
inputs = [
    torch.tensor([0.0, 0.0]),
    torch.tensor([0.0, 1.0]),
    torch.tensor([1.0, 0.0]),
    torch.tensor([1.0, 1.0])
]

# Define weights & bias for AND Gate
w = torch.tensor([1.0, 1.0])
b = torch.tensor(-1.5)

# AND Gate
def and_gate(x):
    return (torch.dot(w, x) + b >= 0).float()

print("AND Gate")
for x in inputs:
    print(x, "->", and_gate(x).item())
        

# Define weights & bias for AND Gate
w = torch.tensor([1.0, 1.0])
b = torch.tensor(-0.5)

# OR Gate
def or_gate(x):
    return (torch.dot(w, x) + b >= 0).float()

print("OR Gate")
for x in inputs:
    print(x, "->", or_gate(x).item())

AND Gate
tensor([0., 0.]) -> 0.0
tensor([0., 1.]) -> 0.0
tensor([1., 0.]) -> 0.0
tensor([1., 1.]) -> 1.0
OR Gate
tensor([0., 0.]) -> 0.0
tensor([0., 1.]) -> 1.0
tensor([1., 0.]) -> 1.0
tensor([1., 1.]) -> 1.0
